### PR TITLE
LRQA-81717 | master

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://liferay.atlassian.net/browse/LRQA-81717

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
ci:stop

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
