### PR TITLE
LRQA-80181 CI Test

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://liferay.atlassian.net/browse/LRQA-80181

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:security

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/139199

**Pull request closed without merging**
