### PR TITLE
LPS-158992 | master

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://issues.liferay.com/browse/LPS-160177

### CODE REVIEW

**Comment by JingyuanZhao** [comment]
ci:test:sf

**Comment by JingyuanZhao** [comment]
ci:test

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test

**Pull request closed without merging**
